- name: Variable
  hosts: WEB
  vars:
    URL: google.com
  tasks:
    - name: Print variable
      ansible.builtin.debug:
        msg: URL = {{ URL }}
  # Ansible access variable with 2 flower brackets

- name: Print task variable
  ansible.builtin.debug:
    msg: URL = {{ URL }}
  vars:
     URL: tasks.google.com

