- name: Demo on conditions
  hosts: all
  tasks:
    - name: Print Fruit Name
      ansible.builtin.debug:
        msg: Fruits Name - Apple

    - name: Print Vegetable Name
      ansible.builtin.debug:
        msg: Fruits Name - Carrot
